version: '2'
services:
    prototypeapp-app:
        image: prototypeapp
        external_links:
            - prototypeapp-postgresql:postgresql
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/prototypeApp
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    prototypeapp-postgresql:
        extends:
            file: postgresql.yml
            service: prototypeapp-postgresql
